# Jekyll Text Theme 全站美化配置
# 仓库：wui-git / fox-lulloon.io
# 访问：https://wui-git.github.io/fox-lulloon.io/

## 站点外观
text_skin: forest
highlight_theme: default

## 网站域名 & 根路径
url     : https://wui-git.github.io
baseurl : /fox-lulloon.io

## 首页标题 & 文艺标语
title   : 狐狸诗意小筑
description: >
  山野自有风，人间自有诗。

## 语言与时区
lang: zh-CN
timezone: Asia/Shanghai

## 作者信息 + 侧边栏文艺简介
author:
  type      : person
  name      : Wuli·Fox
  avatar    : /assets/头像.png
  bio       : 温旧书，煮清茶，守一方诗意人间。
  email     :
  github    : wui-git
  weibo     :
  zhihu     :

## GitHub 仓库绑定
repository: wui-git/fox-lulloon.io
repository_tree: master

## 页面默认路径
paths:
  root    : /
  home    : /
  archive : /archive.html
  rss     : /feed.xml

## 文章设置
excerpt_separator: <!--more-->
license: CC-BY-NC-4.0

toc:
  selectors: h1,h2,h3

## 高级功能开启
mathjax: true
mathjax_autoNumber: true
mermaid: true
chart: true

## 每页文章数
paginate: 6
paginate_path: /page:num

## 静态资源源
sources: bootcdn

## 文章分享
sharing:
  provider: addtoany

## Valine 评论美化
comments:
  provider: valine
  valine:
    app_id      : Favohrffq0ZtxDphpXUChnqd-gzGzoHsz
    app_key     : UYaxXCIA2w4u0bNHJGboO4nn
    placeholder : 山河辽阔，有幸相逢～

## 文章阅读量统计
pageview:
  provider: leancloud
  leancloud:
    app_id    : Favohrffq0ZtxDphpXUChnqd-gzGzoHsz
    app_key   : UYaxXCIA2w4u0bNHJGboO4nn
    app_class : test

## 站内搜索
search:
  provider: default

## 统计分析
analytics:
  provider: false

## 编译渲染规则
markdown    : kramdown
highlighter : rouge
permalink   : date

## 忽略打包文件
exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true

## 插件列表
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji