# Jekyll Text Theme 博客配置
# 仓库：wui-git / fox-lulloon.io
# 访问：https://wui-git.github.io/fox-lulloon.io/

## 站点基础
text_skin: forest
highlight_theme: default

url     : https://wui-git.github.io
baseurl : /fox-lulloon.io

title   : Fox 诗意小筑
description: >
  心有山海，静而不争；以文为友，自律生长。

## 语言与时区
lang: zh-CN
timezone: Asia/Shanghai

## 作者信息 侧边栏展示
author:
  type      : person
  name      : Wuli·Fox
  avatar    : /assets/头像.png
  bio       : 热爱自由，偏爱浪漫，永远保持清醒与温柔。
  email     :
  github    : wui-git
  weibo     :
  zhihu     :

## 仓库关联
repository: wui-git/fox-lulloon.io
repository_tree: master

## 路径
paths:
  root    : /
  home    : /
  archive : /archive.html
  rss     : /feed.xml

## 文章设置
excerpt_separator: <!--more-->
license: CC-BY-NC-4.0

toc:
  selectors: h1,h2,h3

## 高级功能开启
mathjax: true
mathjax_autoNumber: true
mermaid: true
chart: true

## 分页
paginate: 6
paginate_path: /page:num

## 资源源
sources: bootcdn

## 分享
sharing:
  provider: addtoany

## 评论美化
comments:
  provider: valine
  valine:
    app_id      : Favohrffq0ZtxDphpXUChnqd-gzGzoHsz
    app_key     : UYaxXCIA2w4u0bNHJGboO4nn
    placeholder : 山河辽阔，有幸相逢，留一句心事～

## 阅读量
pageview:
  provider: leancloud
  leancloud:
    app_id    : Favohrffq0ZtxDphpXUChnqd-gzGzoHsz
    app_key   : UYaxXCIA2w4u0bNHJGboO4nn
    app_class : test

## 搜索
search:
  provider: default

## 统计
analytics:
  provider: false

## 编译规则
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true

## 插件
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji